name: 'Release Manager'
description: 'Gets latest tag from repo, applies patch increment and makes a new release'
inputs:
  GITHUB_TOKEN:
    description: 'Github auth token'
    required: true
  repo:
    description: 'Github repo name'
    required: true
  owner:
    description: 'Github repo owner'
    required: true
    default: 'World'
outputs:
  nextTagName:
    description: 'Next Tag Name'
runs:
  using: 'node12'
  main: 'dist/index.js'